host = localhost
port = 6601
music-dir = /home/tiago/music/
scale = 200
text-topic = WIRED SOUNDS
text-play = AWAKE <b>%t</b>\nby <i>%a</i>
text-pause = DEAD <b>%t</b>\nby <i>%a</i>
text-stop = PROCESS EXITED
timeout = 5